version: "3.0"

services:
  resource-processor-app:
    image: resource-processor-app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resource-processor-app-microservices_course
    environment:
      SPRING_CLOUD_CONFIG_URI: ${SPRING_CLOUD_CONFIG_URI}
    networks:
      - service-configuration_default
      - service-registry_default
      - resource-service_rabbitmq

networks:
  service-registry_default:
    external: true
  resource-service_rabbitmq:
    external: true
  service-configuration_default:
    external: true
