version: "3.0"

services:
  resource-processor-app:
    image: resource-processor-app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resource-processor-app-microservices_course
    environment:
      SPRING_RABBITMQ_HOST: ${RABBITMQ_HOST}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
    networks:
      - service-registry_default
      - resource-service_rabbitmq

networks:
  service-registry_default:
    external: true
  resource-service_rabbitmq:
    external: true
