spring:
  cloud:
    stream:
      bindings:
        onReceive-in-0:
          destination: resource-ids
          group: resource-processor
          consumer:
            max-attempts: 2             # failed messages are delivered to the DLQ after retries are exhausted.
      rabbit:
        bindings:
          onReceive-in-0:
            consumer:
              autoBindDlq: true         # set to true to enable DLQ
              republish-to-dlq: true    # to know the exact exception of the last error; will add detailed exception and exception stack information in the message header
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8090
  restTemplate:
    connectTimeoutMilliSeconds: 2000
    readTimeoutMilliSeconds: 2000
    maxRetryAttempts: 2
    retryDelayMilliSeconds: 10

services:
  url:
    resource-service: http://localhost:8080/api/v1/resources
    song-service: http://localhost:8081/api/v1/songs

logging:
  level:
    root: info
